heat_template_version: '2016-04-08'

parameters:
  taas_ts_port:
    type: string
    default: taas_ts_port

  left_port:
    type: string
    default: left_port

resources:
  ts_resource:
    type: OS::Neutron::TapService
    properties:
      name: 'test_tap_service'
      description: 'desc'
      port: {get_param: taas_ts_port}
  tf_resource:
    type: OS::Neutron::TapFlow
    properties:
      name: 'test_tap_flow'
      description: 'desc'
      port: {get_param: left_port}
      tap_service: { get_resource: ts_resource }
      direction: 'BOTH'
